services:
  lti-provider:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: pnpm run start:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
